import { NextResponse } from 'next/server';
import countriesData from '@/lib/data/countries.json';

/**
 * Country list is served from a committed static dataset
 * (generated by `npm run build:countries`) — REST Countries v3.1
 * was deprecated in 2026 and v5 requires an API key.
 */
export async function GET() {
  return NextResponse.json(countriesData.countries, {
    headers: { 'Cache-Control': 'public, s-maxage=604800, stale-while-revalidate=86400' },
  });
}
