export const BOOT_LINES = [
  'HMWWCT v3.0 — HOW MUCH WOULD A WAR COST THERE',
  'INITIALIZING WORLD BANK API .................. OK',
  'INITIALIZING SIPRI MILITARY EXPENDITURE ...... OK',
  'INITIALIZING UNHCR DISPLACEMENT RATIOS ....... OK',
  'INITIALIZING FRED COMMODITY PRICES ........... OK',
  'INITIALIZING WATSON INSTITUTE BENCHMARKS ..... OK',
  'LOADING 194 COUNTRY PROFILES ................. OK',
  '',
  '> WARNING: THIS IS NOT A GAME.',
  '> WARNING: THESE NUMBERS ARE REAL.',
  '',
  '> READY.',
];
